apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "acapy.fullname" . }}
  labels:
    {{- include "acapy.labels" . | nindent 4 }}
data:
  acapy-static-args.yaml: |
    auto-accept-invites: {{ .Values.acapy.staticArgs.autoAcceptInvites }}
    auto-accept-requests: {{ .Values.acapy.staticArgs.autoAcceptRequests }}
    auto-respond-messages: {{ .Values.acapy.staticArgs.autoRespondMessages }}
    auto-respond-credential-proposal: {{ .Values.acapy.staticArgs.autoRespondCredentialProposal }}
    auto-respond-credential-offer: {{ .Values.acapy.staticArgs.autoRespondCredentialOffer }}
    auto-respond-credential-request: {{ .Values.acapy.staticArgs.autoRespondCredentialRequest }}
    auto-respond-presentation-proposal: {{ .Values.acapy.staticArgs.autoRespondPresentationProposal }}
    auto-respond-presentation-request: {{ .Values.acapy.staticArgs.autoRespondPresentationRequest }}
    auto-store-credential: {{ .Values.acapy.staticArgs.autoStoreCredential }}
    auto-verify-presentation: {{ .Values.acapy.staticArgs.autoVerifyPresentation }}
    auto-ping-connection: {{ .Values.acapy.staticArgs.autoPingConnection }}
    auto-provision: {{ .Values.acapy.staticArgs.autoProvision }}
    auto-disclose-features: {{ .Values.acapy.staticArgs.autoDiscloseFeatures }}
    notify-revocation: {{ .Values.acapy.staticArgs.notifyRevocation }}
    monitor-revocation-notification: {{ .Values.acapy.staticArgs.monitorRevocationNotification }}
    monitor-ping: {{ .Values.acapy.staticArgs.monitorPing }}
    enable-undelivered-queue: {{ .Values.acapy.staticArgs.enableUndeliveredQueue }}
    exch-use-unencrypted-tags: {{ .Values.acapy.staticArgs.exchUseUnencryptedTags }}
    preserve-exchange-records: {{ .Values.acapy.staticArgs.preserveExchangeRecords }}
    public-invites: {{ .Values.acapy.staticArgs.publicInvites }}
    plugin: 'aries_cloudagent.messaging.jsonld'
    outbound-transport: http
    wallet-type: {{ .Values.acapy.staticArgs.walletType }}
    log-level: {{ .Values.acapy.staticArgs.logLevel }}
