{{- if .Values.bpa.ingress.enabled -}}
{{- $fullName := include "bpa.fullname" . -}}
{{- $svcPort := .Values.bpa.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "bpa.labels" . | nindent 4 }}
  {{- with .Values.bpa.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.bpa.ingress.tls }}
  tls:
    {{- range .Values.bpa.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.bpa.ingress.hosts -}}
    {{- range .Values.bpa.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- else }}
    - host: {{ include "bpa.host" . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}         
{{- end -}}
{{- end }}