{{- if eq (include "bpa.ux.override" .) "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bpa.fullname" . }}-ux
  labels:
    {{- include "bpa.labels" . | nindent 4 }}
data:
  ux.yml: |-
    bpa:
      ux:
{{- if eq .Values.ux.preset "custom" }}
{{ toYaml .Values.ux.config | indent 8 }}
{{- else if eq .Values.ux.preset "bcgov" }}
        buttons:
          primary:
            text: false
            outlined: false
          secondary:
            text: true
            outlined: true
        theme:
          dark: false
          themes:
            light:
              primary: '#003366'
              secondary: '#003366'
              accent: '#82B1FF'
              error: '#D8292F'
              info: '#2196F3'
              success: '#2E8540'
              warning: '#FFC107'
              bgLight: "#FAFAFA"
              bgLight2: "#ECECEC"
              font: "#313132"
              anchor: "#1A5A96"
              anchorHover: "#3B99FC"
              icons: "#003366"
        favicon:
          href: "https://raw.githubusercontent.com/bcgov/common-forms-toolkit/master/app/frontend/public/favicon.ico"
        navigation:
          avatar:
            agent:
              enabled: true
              default: false
              src: "https://raw.githubusercontent.com/bcgov/mines-digital-trust/main/assets/bcgov-logos/BCID_H_rgb_pos.png"
              showName: true
          settings:
            location: "bottom"
          about:
            enabled: true
          logout:
            enabled: false
        header:
          logout:
            enabled: true
{{- end -}}
{{- end -}}
