
{{- if and (not .Values.postgresql.enabled) (not .Values.global.persistence.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "global.postgresql.fullname" . }}
  labels:
    app: {{ template "global.name" . }}
    chart: {{ template "global.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
{{- end -}}